sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env -c biocore python=$PYTHON_VERSION nose flake8 scikit-bio seaborn statsmodels
  - source activate test-env
  - pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2-types/archive/master.zip https://github.com/qiime2/q2-feature-table/archive/master.zip
  - pip install .
  - 'echo "backend: Agg" > matplotlibrc'
script:
  - nosetests
  - flake8 q2_diversity setup.py
